In [4]:
import numpy as np
import sklearn

In [3]:
precip_2002_2013 = np.array([[1.07, 0.44, 1.5],
                              [0.27, 1.13, 1.72]])
# two-dimensional array with 2 rows and 3 columns
precip_2002_2013

array([[1.07, 0.44, 1.5 ],
       [0.27, 1.13, 1.72]])

In [6]:
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [14]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [15]:
print("x3 ndim: ", x2.ndim)
print("x3 shape:", x2.shape)
print("x3 size: ", x2.size)

x3 ndim:  2
x3 shape: (3, 4)
x3 size:  12


In [21]:
# Flatten a NumPy Array
arr = np.array([[1, 2], [3, 4]])
print(arr)
arr1 = np.ravel(arr)


[[1 2]
 [3 4]]


In [25]:
np.ravel(arr, order="F")

array([1, 3, 2, 4])

In [26]:
# Use List to Change the Positions of Rows or Columns in a NumPy Arra
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
new_row_position = [1, 2, 0]
new_arr = arr[new_row_position, :]
new_arr

array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

### Array Slicing: Accessing Subarrays

In [30]:
# One-dimensional subarrays
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
print(x[:5])  # first five elements
print(x[5:])  # elements after index 5
print(x[5:7])  # middle sub-array
print(x[::2])  # every other element
print(x[1::2])  # every other element, starting at index 1

[0 1 2 3 4]
[5 6 7 8 9]
[5 6]
[0 2 4 6 8]
[1 3 5 7 9]


In [40]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [41]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

### Multi-dimensional subarrays

In [42]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [45]:
x2[:2, :3]  # two rows, three columns

array([[3, 5, 2],
       [7, 6, 8]])

In [47]:
x2[:, ::2]  # all rows, every other column

array([[3, 2],
       [7, 8],
       [1, 7]])